package view;

import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Component;
import java.awt.Dimension;
import java.awt.FlowLayout;
import java.awt.Font;
import java.awt.Image;
import java.io.ByteArrayInputStream;
import java.io.IOException;
import java.util.Base64;
import java.util.List;
import java.util.concurrent.ExecutionException;

import javax.imageio.ImageIO;
import javax.swing.BorderFactory;
import javax.swing.BoxLayout;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.SwingUtilities;
import javax.swing.SwingWorker;
import javax.swing.WindowConstants;

import data_access.outfit_image_generation.OutfitImageGenerationDataAccessObject;
import entity.User;
import interface_adapter.outfit_image_generation.OutfitImageGenerationController;
import interface_adapter.outfit_image_generation.OutfitImageGenerationPresenter;
import interface_adapter.outfit_image_generation.OutfitImageGenerationView;
import use_case.outfit_image_generation.OutfitImageGenerationInputBoundary;
import use_case.outfit_image_generation.OutfitImageGenerationInteractor;

/**
 * Window that displays a scrollable gallery of outfit images generated by Gemini.
 */
// -@cs[ClassDataAbstractionCoupling] this UI class naturally uses many Swing and AWT types
public class OutfitImageGalleryPanel extends JFrame implements OutfitImageGenerationView {

    private static final int BORDER_TOP = 5;
    private static final int BORDER_LEFT = 15;
    private static final int BORDER_BOTTOM = 5;
    private static final int BORDER_RIGHT = 15;

    private static final int WINDOW_WIDTH = 420;
    private static final int WINDOW_HEIGHT = 500;

    private static final int LAYOUT_GAP = 10;
    private static final int GRID_H_GAP = 15;
    private static final int GRID_V_GAP = 15;

    private static final int CARD_WIDTH = 380;
    private static final int CARD_HEIGHT = 380;

    private static final int STATUS_FONT_SIZE = 12;
    private static final int TITLE_FONT_SIZE = 14;

    private static final int IMAGE_WIDTH = 360;
    private static final int IMAGE_HEIGHT = 320;
    private static final int AUTO_HEIGHT = -1;

    private final OutfitImageGenerationController controller;
    private final List<String> outfits;

    private final JPanel imageGrid;
    private final JLabel statusLabel = new JLabel(" ");

    /**
     * Constructs the gallery window.
     *
     * @param currentUser the logged-in user
     * @param outfits     list of outfit description strings
     */
    public OutfitImageGalleryPanel(User currentUser, List<String> outfits) {
        this.outfits = outfits;

        final OutfitImageGenerationPresenter presenter =
                new OutfitImageGenerationPresenter(this);
        final OutfitImageGenerationDataAccessObject dataAccess =
                new OutfitImageGenerationDataAccessObject(currentUser);
        final OutfitImageGenerationInputBoundary interactor =
                new OutfitImageGenerationInteractor(dataAccess, presenter);
        this.controller = new OutfitImageGenerationController(interactor);

        this.imageGrid = new JPanel(new FlowLayout(FlowLayout.LEFT, GRID_H_GAP, GRID_V_GAP));

        setTitle("Outfit Image Gallery");
        setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);
        setLayout(new BorderLayout(LAYOUT_GAP, LAYOUT_GAP));

        final JScrollPane scrollPane = new JScrollPane(imageGrid);
        add(scrollPane, BorderLayout.CENTER);

        final JPanel statusPanel = new JPanel(new BorderLayout());
        statusPanel.setBorder(BorderFactory.createEmptyBorder(
                BORDER_TOP, BORDER_LEFT, BORDER_BOTTOM, BORDER_RIGHT));
        statusLabel.setFont(new Font("Arial", Font.ITALIC, STATUS_FONT_SIZE));
        statusPanel.add(statusLabel, BorderLayout.WEST);
        add(statusPanel, BorderLayout.SOUTH);

        setSize(WINDOW_WIDTH, WINDOW_HEIGHT);
        setLocationRelativeTo(null);

        requestImages();
    }

    /**
     * Starts an asynchronous request to generate images.
     */
    private void requestImages() {
        statusLabel.setText("Generating images...");
        statusLabel.revalidate();
        statusLabel.repaint();

        imageGrid.revalidate();
        imageGrid.repaint();

        final SwingWorker<Void, Void> worker = new SwingWorker<Void, Void>() {
            @Override
            protected Void doInBackground() {
                controller.generateImages(outfits);
                return null;
            }
        };
        worker.execute();
    }

    /**
     * Called when image generation succeeds.
     *
     * @param base64Images list of base64-encoded PNG images
     */
    @Override
    public void onImageGenerationSuccess(List<String> base64Images) {
        SwingUtilities.invokeLater(() -> handleImageGenerationSuccess(base64Images));
    }

    private void handleImageGenerationSuccess(List<String> base64Images) {
        statusLabel.setText("Images loaded successfully!");

        imageGrid.removeAll();

        for (int i = 0; i < base64Images.size(); i++) {
            final String base64 = base64Images.get(i);

            final JPanel card = new JPanel();
            card.setLayout(new BoxLayout(card, BoxLayout.Y_AXIS));
            card.setBorder(BorderFactory.createLineBorder(Color.GRAY));
            card.setPreferredSize(new Dimension(CARD_WIDTH, CARD_HEIGHT));

            final JLabel title = new JLabel("Outfit " + (i + 1), JLabel.CENTER);
            title.setFont(new Font("Arial", Font.BOLD, TITLE_FONT_SIZE));
            title.setAlignmentX(Component.CENTER_ALIGNMENT);
            card.add(title);

            final JLabel imgLabel = new JLabel("Loading image...", JLabel.CENTER);
            imgLabel.setPreferredSize(new Dimension(IMAGE_WIDTH, IMAGE_HEIGHT));
            imgLabel.setAlignmentX(Component.CENTER_ALIGNMENT);
            card.add(imgLabel);

            loadBase64ImageAsync(base64, imgLabel);

            imageGrid.add(card);
        }

        imageGrid.revalidate();
        imageGrid.repaint();
    }

    private void loadBase64ImageAsync(String base64, JLabel targetLabel) {
        final ImageLoaderWorker worker = new ImageLoaderWorker(base64, targetLabel);
        worker.execute();
    }

    /**
     * Called when image generation fails.
     *
     * @param errorMessage the error message to display
     */
    @Override
    public void onImageGenerationFailure(String errorMessage) {
        SwingUtilities.invokeLater(() -> {
            statusLabel.setText("Failed to load images.");
            JOptionPane.showMessageDialog(
                    this,
                    errorMessage,
                    "Image Error",
                    JOptionPane.ERROR_MESSAGE
            );
        });
    }

    /**
     * Background worker that decodes a base64 image and updates the label.
     */
    private static class ImageLoaderWorker extends SwingWorker<ImageIcon, Void> {

        private final String base64;
        private final JLabel targetLabel;

        ImageLoaderWorker(String base64, JLabel targetLabel) {
            this.base64 = base64;
            this.targetLabel = targetLabel;
        }

        @Override
        protected ImageIcon doInBackground() {
            ImageIcon result = null;

            try {
                final byte[] decoded = Base64.getDecoder().decode(base64);
                final ByteArrayInputStream bais = new ByteArrayInputStream(decoded);
                final Image img = ImageIO.read(bais);
                if (img != null) {
                    result = new ImageIcon(
                            img.getScaledInstance(IMAGE_WIDTH, AUTO_HEIGHT, Image.SCALE_SMOOTH));
                }
            }
            catch (IllegalArgumentException ex) {
                // invalid base64 or image; keep result as null
            }
            catch (IOException ex) {
                // IO problem; keep result as null
            }

            return result;
        }

        @Override
        protected void done() {
            try {
                final ImageIcon icon = get();
                if (icon != null) {
                    targetLabel.setText("");
                    targetLabel.setIcon(icon);
                }
                else {
                    targetLabel.setText("Failed to load image");
                    targetLabel.setForeground(Color.RED);
                }
            }
            catch (InterruptedException ex) {
                Thread.currentThread().interrupt();
            }
            catch (ExecutionException ex) {
                targetLabel.setText("Failed to load image");
                targetLabel.setForeground(Color.RED);
            }
        }
    }
}
